### ISSUE TITLE
docbook XSL not found at compile time

### ISSUE THREAD

**Issue by m09** [Keruspe/creds#1]
Had to install the package `docbook-xsl` on Ubuntu 14.04 LTS so that creds would build its manpage. Otherwise it failed with the error:

```
$ make
  GEN      man/1/creds.1
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
make: *** [man/1/creds.1] Error 4
```

Maybe there's some way to check for the dependency at configure time or something!

Cheers :)

**Comment by Keruspe** [comment]
This is from a git clone, right?
From a tarball, man-pages are shipped so unless I'm missing something, they shouldn't be built.

I can't think of an easy way to detect this at configure time, and from what I've read, no other project using docbook are checking for it either. (I'm pretty sure it's a runtime dep of xsltproc for the majority of distros, apart from ubuntu it seems)

**Comment by Keruspe** [comment]
Hmm, actually it was regenerated from a tarball too for now.

I just fixed that, will do another release soon-ish
